version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
