name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Install Playwright Browsers
        run: apt update && npx playwright install --with-deps

      - name: Lint source files
        run: bun run lint

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun run test
